# Generated by Django 4.0.2 on 2022-02-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionsRules', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choic',
            new_name='Choices',
        ),
    ]
