# Generated by Django 3.2.12 on 2023-04-22 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionsRules', '0002_rename_choic_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='create date')),
            ],
        ),
        migrations.CreateModel(
            name='LotteryOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lottery_options_text', models.CharField(max_length=200)),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionsRules.lottery')),
            ],
        ),
    ]
