# Generated by Django 3.2.12 on 2023-07-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionsRules', '0003_lottery_lotteryoptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lottery',
            old_name='question_text',
            new_name='Lottery_text',
        ),
    ]
